[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "always"

# キューワーカーを定期実行
[[services]]
name = "queue-worker"
command = "php artisan queue:work --tries=3 --timeout=90 --daemon"
restartPolicy = "always"

# Cronジョブでキューを処理
[[cron]]
schedule = "* * * * *"  # 毎分実行
command = "php artisan queue:work --once --tries=3" 